// All player-visible strings. UI language: Spanish (the learner's language).
// Switching UI language = swapping this module's data.
export const STR = {
  title: 'English Rail Runner',
  subtitle: 'Salta al vagón correcto y aprende inglés',
  play: 'JUGAR',
  levels: 'Niveles',
  level: 'Nivel',
  locked: 'Bloqueado',
  translate: 'Traduce:',
  ready: '¡Prepárate!',
  go: '¡Vamos!',
  correct: '¡Correcto!',
  wrong: 'Era:',
  meta: 'META',
  levelComplete: '¡Nivel completado!',
  levelFailed: '¡Te atrapó el dron!',
  wordsLearned: 'Palabras aprendidas',
  accuracy: 'Aciertos',
  coins: 'Monedas',
  streak: 'Racha',
  score: 'Puntos',
  next: 'Siguiente nivel',
  retry: 'Reintentar',
  menu: 'Menú',
  review: 'Repaso',
  reviewComplete: '¡Repaso completado!',
  reviewPending: 'por repasar',
  resume: 'Continuar',
  paused: 'Pausa',
  totalWords: 'palabras aprendidas',
  powerShield: '¡Escudo!',
  powerMagnet: '¡Imán!',
  powerSlow: '¡Cámara lenta!',
  powerX2: '¡Puntos x2!',
  tapToStart: 'Toca para empezar',
  controlsTouch: 'Desliza para moverte, saltar y deslizarte',
  hintMove: 'Desliza a los lados para cambiar de vía',
  hintJump: 'Desliza hacia arriba (o toca) para saltar',
  hintSlide: 'Desliza hacia abajo para agacharte',
  droneWarning: '¡El dron se acerca!',
  best: 'Récord',
  loading: 'Cargando...',
  audioHint: '🔊 toca la pantalla para activar el sonido',
} as const;
